sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.2.1"
  - development

install:
  - haxelib install travix
  - haxelib run travix install
  - git clone https://github.com/mustache/spec

script:
  - haxelib run travix interp
  - haxelib run travix neko
  # - haxelib run travix js
  - haxelib run travix node
  - haxelib run travix php
  - haxelib run travix python
  - haxelib run travix java
  - haxelib run travix cs
  - haxelib run travix cpp
  - haxelib run travix flash -D exit
  - bash demo-deploy.sh
